version: '3'

services:
  app:
    image: golang:alpine
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}/
    volumes:
      - .:/go-echo-mongo
    working_dir: /go-echo-mongo/main
    command: go run main.go

